# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b4e6bdaa7c1e8f43df4087f17c09b9b424602f4fd9aacd53562b3325e9398aff23017bea913a680dc7f1a6406b1b7cd9e72860885dd71f83fcb6498a783ccb7

test:
  secret_key_base: fee009376cc99b5dddefefe7b6273c57c2685bfbb843d117b9b7e4b6b020b6d0087b9506d23a46e6b28cbd6f1390c1a6f5a6ebed0f52a41edd061c7e004497eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
